server:
  port: 9090
spring:
  application:
    name: cyber-done-api-gateway-microservice
springdoc:
  swagger-ui:
    use-root-path: true
    display-query-params: true
security:
  jwt-secret: d2980f58-3d82-4144-b802-406f4b47930b-5784cca4-0b50-425e-ac6c-bd651e0c788d
